import React from 'react';
import { ArtifactState } from '../types';
import { Icons } from './Icons';
import MarkdownRenderer from './MarkdownRenderer';
import { motion } from 'framer-motion';

interface ArtifactPanelProps {
  artifact: ArtifactState;
  isOpen: boolean;
  toggleOpen: () => void;
}

export const ArtifactPanel: React.FC<ArtifactPanelProps> = ({
  artifact,
  isOpen,
  toggleOpen,
}) => {
  if (!artifact.content && !isOpen) return null;

  return (
    <motion.div 
      layout
      initial={{ width: 0, opacity: 0 }}
      animate={{ 
        width: isOpen ? '100%' : '0px',
        opacity: isOpen ? 1 : 0,
      }}
      transition={{ type: "spring", stiffness: 300, damping: 30 }}
      className={`fixed sm:relative right-0 top-0 h-full bg-surface border-l border-border flex flex-col shadow-2xl overflow-hidden z-20 sm:z-0 sm:w-1/2 lg:w-[55%]`}
      style={{ display: isOpen ? 'flex' : 'none' }} // Fallback for hard toggle
    >
      {/* Header */}
      <div className="h-16 border-b border-border flex items-center justify-between px-6 bg-surface/95 backdrop-blur">
        <div className="flex items-center gap-2 text-zinc-300">
          <Icons.FileText className="w-4 h-4" />
          <span className="text-sm font-medium uppercase tracking-wider text-zinc-500">Research Artifact</span>
        </div>
        <div className="flex items-center gap-2">
             {artifact.isStreaming && (
                <div className="flex items-center gap-1.5 bg-blue-500/10 px-2 py-1 rounded text-xs text-blue-400 mr-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-blue-400 animate-pulse"></span>
                    Generating
                </div>
             )}
             <button 
                onClick={toggleOpen}
                className="p-2 hover:bg-zinc-800 rounded-lg text-zinc-500 transition-colors"
             >
                <Icons.Close className="w-4 h-4" />
             </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-8 sm:p-12 bg-[#121214]">
        <div className="max-w-3xl mx-auto">
          <div className="mb-8 pb-4 border-b border-zinc-800">
             <h1 className="text-3xl font-bold text-zinc-50 mb-2">{artifact.title || "New Report"}</h1>
             <div className="flex items-center gap-4 text-xs text-zinc-500">
                <span>{new Date().toLocaleDateString()}</span>
                <span>•</span>
                <span>Generated by DeepRes</span>
             </div>
          </div>
          
          {artifact.content ? (
            <MarkdownRenderer content={artifact.content} className="min-h-[500px]" />
          ) : (
            <div className="flex flex-col items-center justify-center h-64 text-zinc-600 space-y-4">
                <Icons.Loader className="w-8 h-8 animate-spin" />
                <p>Waiting for artifact generation...</p>
            </div>
          )}
          
          {artifact.isStreaming && (
             <div className="mt-4 h-4 w-4 bg-zinc-500 rounded-full animate-pulse" />
          )}
        </div>
      </div>
    </motion.div>
  );
};
